name: CI Pipeline

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.2

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.11

    - name: Install Bandit 
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o py-webapp-ci-pipeline.json

    - name:  Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      if: always()
      with:
        name: bandit-scan-findings
        path: py-webapp-ci-pipeline.json

  image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4.1.2

   - name: Set up Docker
     uses: crazy-max/ghaction-setup-docker@v3.1.0
     
   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

   - name: Docker Scout Scan
     run: |
       curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       sh install-scout.sh
       echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
       docker scout quickview --only-severity high, medium
       docker scout cves --only-severity high, medium



        
        

