name: CI Pipeline

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.2

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.11

    - name: Install Bandit 
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f csv -o py-webapp-ci-pipeline.csv

    - name:  Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      if: always()
      with:
        name: bandit-scan-findings
        path: py-webapp-ci-pipeline.csv

  image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4.1.2

   - name: Set up Docker
     uses: crazy-max/ghaction-setup-docker@v3.1.0
     
   - name: Build Docker Image
     run: docker build -f Dockerfile -t webapp:latest .

   - name: Docker Scout Filtered Scan
     uses: docker/scout-action@v1.6.4
     if: always()
     with:
       dockerhub-user: ${{ secrets.DOCKER_HUB_USERNAME }}
       dockerhub-password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: docker-scout-report.sarif
       # exit-code: true

   - name: Uploading Artifact
     uses: actions/checkout@v4.1.2
     if: always()
     with:
       name: docker-scout-findings
       path: docker-scout-report.sarif
       
       
     

   # - name: Docker Scout Scan
   #   run: |
   #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
   #     sh install-scout.sh
   #     echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
   #     docker scout quickview 
   #     docker scout cves --only-severity high, medium webapp:latest
   #     docker scout recommendation webapp:latest
    



        
        

